[package]
name = "minigrep"
version = "0.1.0"
edition = "2021"
authors = ["Elijah Koulaxis <liakos.koulaxis@yahoo.com>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
